training:
  max_seq_length: 16384
  num_epochs: 3
  learning_rate: 2e-5
  # learning_rate: 0.0002  # Slightly increased
  batch_size: 1
  # batch_size: 2
  gradient_accumulation_steps: 8 # Effective batch size of 4 or 8
  # gradient_accumulation_steps: 4 # Effective batch size of 8
  warmup_steps: 35
  max_steps: 0
  save_steps: 110
  eval_steps: 110
  weight_decay: 0.01
  random_seed: 3407
  packing: false
  train_on_completions: true
  gradient_checkpointing: unsloth # Crucial for 16k context
  optim: adamw_8bit
  lr_scheduler_type: cosine

lora:
  lora_r: 64 # If you are doing highly complex logic or debate tasks, bump this to 64 or 128
  lora_alpha: 64 # Keep this equal to lora_r for Llama models
  lora_dropout: 0
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  use_rslora: true
  use_loftq: false
  finetune_vision_layers: false # Must be false for 3B
  finetune_language_layers: true
  finetune_attention_modules: true
  finetune_mlp_modules: true